s1 = "I have an apple"
print("s1 is :",s1)
print("split()    :",s1.split())
print()
s2 = "Apple,Orange,Banana"
print("s2 is :",s2)
print("split()    :",s2.split())
print("split(',') :",s2.split(","))
print()
s3 = "Orange Apple Banana"
print("s3 is :",s3)
list3 = s3.split()
list3.sort()
s4 = " ".join(list3)
print("s3 after split and list sort :",s4)
s5 = " ".join(sorted(s3.split()))
print("s3 after split and sorted :",s5)
print()
s7 = "I have an apple"      # 3 seperators dividing 4 Substrings
print("s7 is :",s7)
print("split with maxplit 2 :",s7.split(maxsplit=2))
print("rsplit with maxplit 2 :",s7.rsplit(maxsplit=2))
print()
print("No difference in split() and rsplit() if all separators are used...")
print("split() :",s7.split())
print("rsplit() :",s7.rsplit())
print("split() with maxplit 3:",s7.split(maxsplit=3))
print("rsplit() with maxplit 3:",s7.rsplit(maxsplit=3))
print()
